### ISSUE TITLE
Compile times

### ISSUE THREAD

**Issue by EamonKeane** [monzo/ddbt#15]
Interesting repo. Just curious what kind of compile times do you get with ddbt/expect to get? Did you consider improving the existing python repo and decide you couldn't make it as fast as you desired?

**Comment by ucg8j** [comment]
Hi Eamon - apologies on not getting back to you sooner. To answer your questions

>Just curious what kind of compile times do you get with ddbt/expect to get?

At Monzo we have over 4k models to give you some perspective of the scale. The times we get vary but approximately, dbt can take anywhere between 5-15mins whereas ddbt is consistently <1min.

>Did you consider improving the existing python repo and decide you couldn't make it as fast as you desired?

At Monzo our main language is Go. One of our talented Staff Engineers decided one weekend that they'd take a stab at making a super fast Go dbt command line replacement. They did this purposefully never having seen the dbt Python implementation so as not to bias their approach. Turns out it worked like a dream.
We have been in contact with Fishtown Analytics :heart: (authors of dbt) and we have shown them ddbt. Fishtown are currently working on some speed improvements with Python.

**Comment by EamonKeane** [comment]
Thanks for the response. That's a major improvement, well done!
